// GENERATED by `cargo run -p page --example instrument_js` (build.sh); do not edit.
// The loader's recording vocabulary: page/src/loader.rs's closed code lists and craftworks-instrument's tables.
// Every event is STRIDE numbers, [kind, site, a, b, c]; the page validates each against the same lists.
export const STRIDE = 5;
export const EVENT = Object.freeze({ "EDGE": 0, "EXIT": 1, "COUNTER": 2 });
export const SITE = Object.freeze({ "loader::fetch": 0 });
export const KEY = Object.freeze({ "Attempts": 0, "OffsetMs": 1, "StatusClass": 2 });
export const OUTCOME = Object.freeze({ "Timeout": 0, "Withdrawn": 1 });
export const STATUS = Object.freeze({ "Ok": 0, "NotFound": 1, "ServerError": 2, "OtherHttp": 3, "Abort": 4, "NetworkError": 5 });
// An HTTP status's class: the first [lowest, highest, class] that holds it, else STATUS.OtherHttp.
export const HTTP_CLASSES = Object.freeze([[200, 299, 0], [404, 404, 1], [500, 599, 2]]);
// A time, coarsened: round down to the grain of the first [below, grain] band it is under, else COARSEN_LAST_GRAIN.
export const COARSEN_BANDS = Object.freeze([[1000, 10], [60000, 100]]);
export const COARSEN_LAST_GRAIN = 1000;
