// GENERATED by `cargo run -p page --example rto_js` (build.sh); do not edit.
// The page's RTO back-off from no sample (page/src/rto.rs, RFC 6298 §5.5):
// each wait after an unanswered ask, the last repeating for ever.
export const RTO_SCHEDULE_MS = Object.freeze([1000, 2000, 4000, 8000, 16000, 32000, 60000]);
// How many GETs a new page keeps in flight after n answers (page/src/rto.rs `Window`, slow start):
// the load-piece race's pacing (sdk#347). The last entry holds from then on.
export const WINDOW_AFTER_ANSWERS = Object.freeze([4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67]);
// The node's own bounds on a GET (page/src/rto.rs, FREENET-CONSTRAINTS F64): its web path answers 503 after
// NODE_WEB_BOUND_MS and leaves its GET running; one node GET against silent peers runs at most NODE_GET_BOUND_MS (B).
export const NODE_WEB_BOUND_MS = 30000;
export const NODE_GET_BOUND_MS = 240000;
// A non-200 that took STILL_FETCHING_AFTER_MS or more means the node is still fetching; served() re-asks such a
// source STILL_FETCHING_REASK_MS[n] after its n-th such answer, the last repeating (sdk#447).
export const STILL_FETCHING_AFTER_MS = 29900;
export const STILL_FETCHING_REASK_MS = Object.freeze([100, 30000, 60000, 120000, 240000]);
